[workspace]
members = ['examples/*']
resolver = "2"

[workspace.package]
version = "0.1.0"
edition = "2021"

[workspace.dependencies]
tokio = { version = "1.39.0", features = ["full"] }
axum = "0.8.1"
serde = { version = "1.0.215", features = ["derive"] }
serde_json = "1.0.105"
