[package]
name = "custom-deserializer"
version.workspace = true
edition.workspace = true

[dependencies]
axum = { workspace = true }
tokio = { workspace = true }
serde = { workspace = true }
tower = { version = "0.5.2", features = ["util"] }
http-body-util = { version = "0.1.0" }
